replicaCount: 1

image:
  repository: 741452525359.dkr.ecr.us-east-1.amazonaws.com/react-app
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  host: eks-project.com
  annotations:
    kubernetes.io/ingress.class: nginx

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi

storage:
  size: 1Gi
  storageClass: gp2

namespace: eks-project-production
